all: FindDevices NewAddress

FindDevices             :FindDevices.cpp ../iarduino_I2C_pH.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_pH.cpp
getData                 :getData.cpp ../iarduino_I2C_pH.cpp
getFunction             :getFunction.cpp ../iarduino_I2C_pH.cpp
getSettings             :getSettings.cpp ../iarduino_I2C_pH.cpp

clean:
	rm -f FindDevices NewAddress getData getFunction getSettings
